name: Rubber-stamp
on: pull_request_target

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Rubber-stamp
        if: github.actor == 'dependabot[bot]' || github.actor == 'jsoref'
        run: >-
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          gh pr review
          -R $GITHUB_REPOSITORY
          ${{github.event.pull_request.number}}
          --approve -b ':shrug:'
