name: Rubber-stamp
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Rubber-stamp
        if: github.actor == 'dependabot[bot]' || github.actor == 'jsoref'
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} gh pr review --approve -b ':shrug:'
