name: Spell checking
on: [pull_request_target, push, issue_comment]

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - uses: jsoref/check-spelling@prerelease
      with:
        config: .github/actions/spell-check
        experimental_apply_changes_via_bot: 1
